name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Build RetroMUDlet - Shared
        uses: demonnic/build-with-muddler@v1.4
        with:
          workingDir: "${{ github.workspace }}/Shared"
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: RetroMUDlet - Shared
          path: "${{ github.workspace }}/Shared/build/tmp"

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: CI-latest
          files: |
            **/*.zip
                    
