name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Build RetroMUDlet - Shared
        uses: demonnic/build-with-muddler@v1.4
        with:
          working-directory: "${{ github.workspace }}/Shared"
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: RetroMUDlet - Shared
          path: "${{ github.workspace }}/Shared/build/tmp"
